#!/usr/bin/env bash
# Generate THIRD-PARTY-NOTICES per subproject.
#
# Outputs (all committed):
#   services/control-plane/THIRD-PARTY-NOTICES.md
#   services/worker/THIRD-PARTY-NOTICES.md
#   apps/ui/THIRD-PARTY-NOTICES.md
#   docs/THIRD-PARTY-NOTICES.md
#
# Requires: go, cargo, pnpm. Installs go-licenses + cargo-about on demand.
set -euo pipefail

repo_root=$(cd "$(dirname "$0")/.." && pwd)
cd "$repo_root"

echo "==> Go control plane"
if ! command -v go-licenses >/dev/null 2>&1; then
  echo "  installing go-licenses…"
  GOBIN="$repo_root/bin" go install github.com/google/go-licenses@latest
  export PATH="$repo_root/bin:$PATH"
fi
(
  cd services/control-plane
  {
    echo "# Third-party notices — spinup-control-plane"
    echo
    echo "This file is generated by \`scripts/gen-third-party-notices.sh\`. Do not edit by hand."
    echo
    echo "The control plane statically links the Go modules listed below. Each module is used under the license shown; the full text of each license is retained in the module's own source repository (linked)."
    echo
    echo "| Module | Version | License |"
    echo "|---|---|---|"
    go-licenses csv ./cmd/control-plane 2>/dev/null \
      | while IFS=, read -r name url lic; do
          [ -z "$lic" ] && continue
          [ "$lic" = "Unknown" ] && continue
          # Skip our own module
          case "$name" in github.com/emdzej/spinup/*) continue;; esac
          printf "| \`%s\` | — | %s |\n" "$name" "$lic"
        done
  } > THIRD-PARTY-NOTICES.md
  echo "  → services/control-plane/THIRD-PARTY-NOTICES.md ($(wc -l < THIRD-PARTY-NOTICES.md) lines)"
)

echo "==> Rust worker"
if ! command -v cargo-about >/dev/null 2>&1; then
  echo "  installing cargo-about…"
  # `cli` feature is required for the actual `cargo about` binary.
  cargo install --locked --features cli cargo-about
fi
(
  cd services/worker
  # about.toml is expected to be checked in. If not, print a hint and skip.
  if [ ! -f about.toml ]; then
    echo "  services/worker/about.toml missing; create it (see cargo-about docs) and rerun."
    exit 1
  fi
  [ -f about.hbs ] || cat > about.hbs <<'HBS'
# Third-party notices — spinup-worker

This file is generated by `scripts/gen-third-party-notices.sh`. Do not edit by hand.

The worker binary statically links the Rust crates below.

| Crate | Version | License |
|---|---|---|
{{#each crates}}| [`{{package.name}}`]({{#if package.repository}}{{package.repository}}{{else}}https://crates.io/crates/{{package.name}}{{/if}}) | {{package.version}} | {{license}} |
{{/each}}
HBS
  cargo about generate about.hbs > THIRD-PARTY-NOTICES.md 2>/dev/null || {
    echo "  cargo about failed — check about.toml against unrecognized licenses"
    cargo about generate about.hbs || true
  }
  echo "  → services/worker/THIRD-PARTY-NOTICES.md ($(wc -l < THIRD-PARTY-NOTICES.md) lines)"
)

echo "==> UI + docs (pnpm workspaces)"
for pkg in apps/ui docs; do
  (
    cd "$pkg"
    pkg_name=$(node -e 'console.log(require("./package.json").name)')
    {
      echo "# Third-party notices — $pkg_name"
      echo
      echo "This file is generated by \`scripts/gen-third-party-notices.sh\`. Do not edit by hand."
      echo
      echo "The following npm packages ship in the built bundle (or are dev-only tools) under their respective licenses:"
      echo
      echo "| Package | Version | License |"
      echo "|---|---|---|"
      # pnpm licenses list emits JSON; flatten into a table
      pnpm licenses list --json 2>/dev/null | node -e '
        const data = JSON.parse(require("fs").readFileSync(0, "utf8"));
        const rows = [];
        for (const [lic, pkgs] of Object.entries(data)) {
          for (const p of pkgs) rows.push([p.name, p.version || "—", lic]);
        }
        rows.sort();
        for (const [n, v, l] of rows) console.log(`| \`${n}\` | ${v} | ${l} |`);
      '
    } > THIRD-PARTY-NOTICES.md
    echo "  → $pkg/THIRD-PARTY-NOTICES.md ($(wc -l < THIRD-PARTY-NOTICES.md) lines)"
  )
done

echo
echo "Done. Review the generated files, then \`git add\` and commit."
