{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Chart.Name }}-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spinup.labels" . | nindent 4 }}
spec:
  selector:
    {{- toYaml .Values.istio.gatewaySelector | nindent 4 }}
  servers:
    - hosts:
        - {{ .Values.dnsName }}
      port:
        name: https
        number: 443
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: {{ .Values.istio.tls.credentialName | quote }}
    - hosts:
        - {{ .Values.dnsName }}
      port:
        name: http
        number: 80
        protocol: HTTP
      tls:
        httpsRedirect: true
{{- end }}
