{{- if and (not .Values.oci.auth.existingSecret) .Values.oci.auth.inline.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-oci-auth" .Chart.Name }}
  namespace: {{ .Values.functionsNamespace.name }}
  labels:
    {{- include "spinup.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ required "oci.auth.inline.dockerconfigjson is required when inline auth is enabled" .Values.oci.auth.inline.dockerconfigjson | b64enc }}
{{- end }}
