apiVersion: v1
kind: Service
metadata:
  name: {{ include "spinup.controlPlane.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spinup.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "spinup.name" . }}
    app.kubernetes.io/component: control-plane
  ports:
    - name: http
      port: 80
      targetPort: http
